[package]
name = "lazynotes"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
ratatui = "0.26"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
time = { version = "0.3", features = ["macros", "formatting", "local-offset"] }

